<?php

declare(strict_types=1);

namespace app\control;

use myphp\Log;
use rpc\JsonRpcService;
use myphp\Response;

class JsonRpcAct extends \myphp\Control
{
    public function _before()
    {
        Log::Dir('jsonRpc');
        $this->response->setContentType(Response::CONTENT_TYPE_JSON);
        JsonRpcService::$log = true;
        JsonRpcService::$outProtocol = false;
        JsonRpcService::$authKey = GetC('rpc_key');
        JsonRpcService::$allowIp = GetC('rpc_ip');

        if (!JsonRpcService::authHttp()) {
            throw new \Exception('', 403);
            \myphp::send('Unauthorized', 403);
            return false;
        }

        return parent::_before(); // TODO: Change the autogenerated stub
    }
    public function index()
    {
        return JsonRpcService::run($this->request->rawBody());
    }
}
